Downgrade build system to use Node 0.10.
We are still transpiling a number of vendored libraries with
older versions of the es6-module-transpiler (because they are not
immediately compatible with esperanto).

Using es6-module-transpiler on Node 0.11+ (or io.js) results in an error
like the following:

```
Cannot convert a Symbol value to a string
TypeError: Cannot convert a Symbol value to a string
    at RegExp.test (native)
    at Symbol.hasOwnProperty (/home/travis/build/emberjs/ember.js/node_modules/emberjs-build/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:163:43)
    at /home/travis/build/emberjs/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:137:17
    at setToStringTag (/home/travis/build/emberjs/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:93:13)
    at /home/travis/build/emberjs/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:631:3
    at /home/travis/build/emberjs/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:647:2
    at Object.<anonymous> (/home/travis/build/emberjs/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:2260:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

The solution is to update all vendored libs to be compatible with
esperanto.