Revert "improve fn & on undefined callback message"
This reverts commit f6f9f5210754155c8d081a65d78f37a561d928f7.

The changes landed cause failures in CI (I should have rebased the
branch to make sure that the code still worked after the last few
glimmer-vm updates).

```
[0413/140947.176661:INFO:CONSOLE(52)] "    Failed assertion: Promise rejected during " model is tracked": args.positional.at(...).debug is not a function
TypeError: args.positional.at(...).debug is not a function
    at OnModifierState.updateFromArgs (http://localhost:13141/tests/ember.js:9767:68)
    at OnModifierManager.install (http://localhost:13141/tests/ember.js:10002:13)
    at TransactionImpl.commit (http://localhost:13141/tests/ember.js:48873:19)
    at EnvironmentImpl.commit (http://localhost:13141/tests/ember.js:49009:19)
    at inTransaction (http://localhost:13141/tests/ember.js:49167:13)
    at InteractiveRenderer._renderRoots (http://localhost:13141/tests/ember.js:11540:37)
    at InteractiveRenderer._renderRootsTransaction (http://localhost:13141/tests/ember.js:11601:14)
    at InteractiveRenderer._renderRoot (http://localhost:13141/tests/ember.js:11527:12)
    at InteractiveRenderer._appendDefinition (http://localhost:13141/tests/ember.js:11442:12)
    at InteractiveRenderer.appendOutletView (http://localhost:13141/tests/ember.js:11428:12)", source:  (52)
```