[BUGFIX lts] Enable _some_ recovery of errors thrown during render.
If `env.commit()` is not called after it has started, and another
`env.begin()` starts Glimmer throws an error:

```
Error: a glimmer transaction was begun, but one already exists. You may have a nested transaction
```

This commit works around the issue by ensuring that if a transaction had
been started, it is cleaned up even if an error was thrown during render.

(cherry picked from commit 11bec3f6f3c72174c5a5d025e92ac8838749fe31)
(cherry picked from commit d1382e3866578d86ebe2281c2843c97dcb64619c)