syntax/parser: Add missing import
lib/parser.ts(16,14): error TS4023: Exported variable 'syntax' has or is using name 'BaseNode' from external module "glimmer/packages/@glimmer/syntax/lib/types/nodes" but cannot be named.

lib/parser.ts(16,14): error TS4023: Exported variable 'syntax' has or is using name 'NodeVisitor' from external module "glimmer/packages/@glimmer/syntax/lib/traversal/traverse" but cannot be named.