[BUGFIX release] Ensure legacy build of template compiler can be loaded.
Without this change the following error was triggered:

```
node -e 'require("ember-source/dist/legacy/ember-template-compiler")'
/Users/rjackson/src/emberjs/ember.js/dist/legacy/ember-template-compiler.js:21
      throw new Error('Could not find module ' + name + ' required by: ' + referrerName);
      ^

Error: Could not find module ember-babel required by: @glimmer/compiler
    at missingModule (/Users/rjackson/src/emberjs/ember.js/dist/legacy/ember-template-compiler.js:21:13)
    at internalRequire (/Users/rjackson/src/emberjs/ember.js/dist/legacy/ember-template-compiler.js:45:7)
    at internalRequire (/Users/rjackson/src/emberjs/ember.js/dist/legacy/ember-template-compiler.js:58:22)
    at internalRequire (/Users/rjackson/src/emberjs/ember.js/dist/legacy/ember-template-compiler.js:58:22)
    at internalRequire (/Users/rjackson/src/emberjs/ember.js/dist/legacy/ember-template-compiler.js:58:22)
    at internalRequire (/Users/rjackson/src/emberjs/ember.js/dist/legacy/ember-template-compiler.js:58:22)
    at internalRequire (/Users/rjackson/src/emberjs/ember.js/dist/legacy/ember-template-compiler.js:58:22)
    at requireModule (/Users/rjackson/src/emberjs/ember.js/dist/legacy/ember-template-compiler.js:99:14)
    at /Users/rjackson/src/emberjs/ember.js/dist/legacy/ember-template-compiler.js:14842:92
    at Object.<anonymous>
    (/Users/rjackson/src/emberjs/ember.js/dist/legacy/ember-template-compiler.js:14845:2)
```

This happened because the `ember-template-compiler.js` bundle did not
include the babel helpers needed.