[BUGFIX beta] Prevent errors when using const `(get arr 1)`.
Prior to this change, calling `{{get arr 1}}` would throw an error:

```
 pathReference.value(...).split is not a function
```

This commit fixes that, by only attempting to `.split` when the
underlying value is not actually a string.

`Ember.get` / `Ember.set` are also updated to allow `get(obj, 2)`
(previously allowed only string keys).